version: "3"
services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      ServerIP: 192.168.0.147
      # IPv6 Address if your network supports it
      #ServerIPv6: 192.168.1.55
      # jwilder/proxy envs, see readme for more info
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.chernobyl.xyz
      VIRTUAL_PORT: 80
      WEBPASSWORD: asdf1234
      DNS1: 9.9.9.9
      DNS2: 1.1.1.1
    # Add your own custom hostnames you need for your domain
    extra_hosts:
      #   Point any of the jwilder virtual_host addresses
      # to your docker host ip address
      - 'pihole.chernobyl.xyz:192.168.0.147'
    volumes:
      - '/etc/pihole/:/etc/pihole/'
      # WARNING: if this log don't exist as a file on the host already
      # docker will try to create a directory in it's place making for lots of errors
      - '/var/log/pihole.log:/var/log/pihole.log'
    restart: always
